annotations:
  catalog.cattle.io/certified: partner
  catalog.cattle.io/display-name: Migrations Operator
  catalog.cattle.io/kube-version: '>= 1.24.0-0'
  catalog.cattle.io/release-name: migrations-operator
  helm.sh/resource-policy: keep
apiVersion: v2
appVersion: 1.2.5
description: Kubernetes operator to manage database migrations
home: https://github.com/AndreaTrendafilov/migrations-operator
kubeVersion: '>= 1.24.0-0'
maintainers:
- name: Andrea Trendafilov
name: migrations-operator
sources:
- https://github.com/AndreaTrendafilov/migrations-operator
type: application
version: 1.0.1
