name: YAML Lint

on:
  pull_request:
  push:
  
jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install dependencies
      run: npm install js-yaml
    - name: Lint YAML files
      run: |
        npx js-yaml -t $(find . -name '*.yml' -o -name '*.yaml')
